export const audioFiles = [
  'sfx/armour_1.m4a',
  'sfx/armour_2.m4a',
  'sfx/armour_3.m4a',
  'sfx/armour_4.m4a',
  'sfx/armour_5.m4a',
  'sfx/brush.m4a',
  'sfx/click.m4a',
  'sfx/gold_1.m4a',
  'sfx/gold_2.m4a',
  'sfx/jewellery_1.m4a',
  'sfx/jewellery_2.m4a',
  'sfx/jewellery_3.m4a',
  'sfx/jewellery_4.m4a',
  'sfx/jewellery_5.m4a',
  'sfx/jewellery_6.m4a',
  'sfx/scroll_1.m4a',
  'sfx/scroll_2.m4a',
  'sfx/scroll_3.m4a',
  'sfx/smith_1.m4a',
  'sfx/smith_2.m4a',
  'sfx/smith_3.m4a',
  'sfx/swoosh_down.m4a',
  'sfx/swoosh_up.m4a',
  'sfx/swoosh.m4a'
].map(f => `/audio/${f}`);